### ISSUE TITLE
at modules.zendframework.com

### ISSUE THREAD

**Issue by runphp** [EvanDotPro/EdpGithub#11]
Fatal error: Call to a member function getBody() on a non-object in /srv/hounddog/var/www/vhosts/modules.zendframework.com/vendor/EdpGithub/src/EdpGithub/Api/AbstractApi.php on line 24

**Comment by ins0** [comment]
this issue is not relevant for this repository and belongs to https://github.com/zendframework/modules.zendframework.com

@EvanDotPro can be closed
