### ISSUE TITLE
Github API Limit reach

### ISSUE THREAD

**Issue by garygitton** [EvanDotPro/EdpGithub#18]
Hi Evan,

On the website http://modules.zendframework.com/ I had couple of time the following error message
```
API rate limit exceeded for 184.105.241.70. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

The message is raised in the file 
```
/var/www/vendor/EdpGithub/src/EdpGithub/Listener/Error.php:74
```

So apparently, the module connect too often to github API. 
Could it be possible to add some cache to avoid the problem?
Or maybe use an other account to connect when exception is raise? 

Thank you,
Gary Gitton

**Comment by ins0** [comment]
this issue is not relevant for this repository and belongs to https://github.com/zendframework/modules.zendframework.com

however this was fixed with https://github.com/zendframework/modules.zendframework.com/issues/288

@EvanDotPro can be closed

**Comment by garygitton** [comment]
You true, it makes sense. I close this issue. 
Gary
