### ISSUE TITLE
Mixing requests POST and GET won't work

### ISSUE THREAD

**Issue by ins0** [EvanDotPro/EdpGithub#23]
mixing requests like 

```
$repoFileContent = $client->api('repos')->content(....); //GET
$markDown = $client->api('markdown')->render($repoFileContent); // POST

//will fail
$repoFileContentFails = $client->api('repos')->content(...); // GET but will use POST
```

as the request http will used from the previous request
https://github.com/EvanDotPro/EdpGithub/blob/master/src/EdpGithub/Http/Client.php#L153

**Comment by Ocramius** [comment]
Absolute code ref: https://github.com/EvanDotPro/EdpGithub/blob/0e66a56cd18f700d922ba538f8c2bf6aa46bf15f/src/EdpGithub/Http/Client.php#L153
