### ISSUE TITLE
Packagist package is outdated

### ISSUE THREAD

**Issue by lku** [EvanDotPro/EdpGithub#35]
Package on packagist.org still pointing to 077b1e2:
https://packagist.org/packages/evandotpro/edp-github

Maybe the GitHub Service Hook is not enabled?

**Comment by gianarb** [comment]
This thing is not in my scope :) 
I ping @EvanDotPro

Thanks! :)

**Comment by gianarb** [comment]
Hi @lku [now is it ok](https://packagist.org/packages/evandotpro/edp-github)? Conferme me and close it please!

Thanks

**Comment by lku** [comment]
@gianarb yes, it is :+1: Thank you!
